/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMulticallable,
  IMulticallableInterface,
} from "../../../../../@ensdomains/ens-contracts/contracts/resolvers/IMulticallable";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "multicall",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "multicallWithNodeCheck",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMulticallable__factory {
  static readonly abi = _abi;
  static createInterface(): IMulticallableInterface {
    return new Interface(_abi) as IMulticallableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMulticallable {
    return new Contract(address, _abi, runner) as unknown as IMulticallable;
  }
}
