/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AlwaysFalseAuthorizer } from "./AlwaysFalseAuthorizer";
export type { AlwaysTrueAuthorizer } from "./AlwaysTrueAuthorizer";
