/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EnsAuthorizerInterface extends Interface {
  getFunction(nameOrSignature: "isAuthorize" | "verified"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isAuthorize",
    values: [AddressLike, string, BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(functionFragment: "verified", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "isAuthorize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verified", data: BytesLike): Result;
}

export interface EnsAuthorizer extends BaseContract {
  connect(runner?: ContractRunner | null): EnsAuthorizer;
  waitForDeployment(): Promise<this>;

  interface: EnsAuthorizerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isAuthorize: TypedContractMethod<
    [
      sender: AddressLike,
      domain: string,
      chainId: BigNumberish,
      addresses: AddressLike[]
    ],
    [boolean],
    "nonpayable"
  >;

  verified: TypedContractMethod<[arg0: string], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isAuthorize"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      domain: string,
      chainId: BigNumberish,
      addresses: AddressLike[]
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verified"
  ): TypedContractMethod<[arg0: string], [string], "view">;

  filters: {};
}
