import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';
import { connectSnap, getSnap } from '../services/snap/snap';
import {Button, Box, Container, FormControl, InputAdornment, InputLabel, TextField, Typography} from "@mui/material";
import { AccountCircle } from '@mui/icons-material';
import '@fontsource/lexend/300.css';
import '@fontsource/lexend/400.css';
import '@fontsource/lexend/500.css';
import '@fontsource/lexend/700.css';

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
      <link href="/favicon.png" rel="icon" />
        <title>Secure Contract Interactions</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />      </Head>
      <main className={styles.main}>
      <Container>
                <Box>
                <Typography className={styles.h2}>Search for Domains</Typography>
                <Typography className={styles.h3}>Register your domain, secure your smart contracts, protect your users. </Typography>
                <div className={styles.boxContainer}>
                    <FormControl className={styles.domainInput}>
                    <TextField className={styles.textInput} label="Your Domain" >
                        <InputAdornment position="end">
                            <AccountCircle />
                        </InputAdornment>
                    </TextField>
                    </FormControl>
                    </div>
                </Box>
            </Container>
      </main>
    </div>
  );
};

export default Home;
