/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVersionableResolver,
  IVersionableResolverInterface,
} from "../../../../../../@ensdomains/ens-contracts/contracts/resolvers/profiles/IVersionableResolver";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newVersion",
        type: "uint64",
      },
    ],
    name: "VersionChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
    ],
    name: "recordVersions",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVersionableResolver__factory {
  static readonly abi = _abi;
  static createInterface(): IVersionableResolverInterface {
    return new Interface(_abi) as IVersionableResolverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVersionableResolver {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IVersionableResolver;
  }
}
