/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMetadataService,
  IMetadataServiceInterface,
} from "../../../../../@ensdomains/ens-contracts/contracts/wrapper/IMetadataService";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "uri",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMetadataService__factory {
  static readonly abi = _abi;
  static createInterface(): IMetadataServiceInterface {
    return new Interface(_abi) as IMetadataServiceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMetadataService {
    return new Contract(address, _abi, runner) as unknown as IMetadataService;
  }
}
