/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ISecureCIRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAddresses"
      | "addAuthorizer"
      | "hasContract"
      | "isDomainWhitelisted"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addAddresses",
    values: [BigNumberish, string, BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addAuthorizer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasContract",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDomainWhitelisted",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAuthorizer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDomainWhitelisted",
    data: BytesLike
  ): Result;
}

export interface ISecureCIRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ISecureCIRegistry;
  waitForDeployment(): Promise<this>;

  interface: ISecureCIRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAddresses: TypedContractMethod<
    [
      authorizer: BigNumberish,
      domain: string,
      chainId: BigNumberish,
      addresses: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;

  addAuthorizer: TypedContractMethod<
    [authorizerId: BigNumberish, authorizer: AddressLike],
    [void],
    "nonpayable"
  >;

  hasContract: TypedContractMethod<
    [chainId: BigNumberish, contractAddress: AddressLike],
    [boolean],
    "nonpayable"
  >;

  isDomainWhitelisted: TypedContractMethod<
    [domainName: string],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAddresses"
  ): TypedContractMethod<
    [
      authorizer: BigNumberish,
      domain: string,
      chainId: BigNumberish,
      addresses: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addAuthorizer"
  ): TypedContractMethod<
    [authorizerId: BigNumberish, authorizer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasContract"
  ): TypedContractMethod<
    [chainId: BigNumberish, contractAddress: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isDomainWhitelisted"
  ): TypedContractMethod<[domainName: string], [boolean], "nonpayable">;

  filters: {};
}
